[package]
name = "zsh-prompt-in-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"] 

[dependencies]
anyhow = "1.0.97"
libc = "0.2.171"
nix = {version = "0.29.0", features = ["signal", "user"]}
smallvec = "1.15.0"

[profile.release]
strip = true
